name: prot_fun
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.11.3
  - matplotlib=3.7.2
  - seaborn=0.13.0
  - scikit-learn=1.3.2
  - tqdm=4.66.5
  - pyyaml=6.0.2
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - cudatoolkit=11.8.0
  - tensorflow=2.13.0
  - tensorflow-addons=0.21.0
  - tensorboard=2.13.0
  - transformers=4.48.0.dev0
  - tokenizers=0.21.0
  - obonet=1.0.0
  - torch-geometric=2.6.1
  - torch-scatter=2.1.2
  - torch-sparse=0.6.18
  - torch-cluster=1.6.3
  - torch-spline-conv=1.2.2
  - requests=2.32.3
  - urllib3=2.2.3
  - fastapi=0.103.1
  - uvicorn=0.23.2

  - jupyterlab=4.3.3
  - notebook=7.3.1
  - ipywidgets=8.1.1
  - pip
  - pip:
      - accelerate==0.33.0
      - datasets==2.20.0
      - evaluate==0.4.2
      - fair-esm==2.0.1
      - huggingface-hub==0.24.5
      - jupyter==1.1.1
      - mlflow==2.8.1
      - networkx==3.2
      - openpyxl==3.1.5
      - proteinflow==2.8.0
      - ray==2.10.0
      - torchsummary==1.5.1
      - wandb==0.18.3

